server:
  tomcat:
    threads:
      max: 200
      min-spare: 100
      max-queue-capacity: 1000

spring:
  application:
    name: payment



payment:
  api:
    secret-key: test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R
  mock:
    total-count: 1000
    plans:
      - attempt: 1
        latency-ms: 1000
        success-count: 1000
        fail-count: 0
        fail-scenarios: []